package hibernate;
// Generated Jan 25, 2018 5:49:05 PM by Hibernate Tools 4.3.1



/**
 * Airplanes generated by hbm2java
 */
public class Airplanes  implements java.io.Serializable {


     private Integer id;
     private String airplanename;
     private int seats;

    public Airplanes() {
    }

    public Airplanes(String airplanename, int seats) {
       this.airplanename = airplanename;
       this.seats = seats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAirplanename() {
        return this.airplanename;
    }
    
    public void setAirplanename(String airplanename) {
        this.airplanename = airplanename;
    }
    public int getSeats() {
        return this.seats;
    }
    
    public void setSeats(int seats) {
        this.seats = seats;
    }




}


