package hibernate;
// Generated Jan 25, 2018 5:49:05 PM by Hibernate Tools 4.3.1



/**
 * Owner generated by hbm2java
 */
public class Owner  implements java.io.Serializable {


     private Integer id;
     private int travellerId;
     private String airlineName;
     private double income;

    public Owner() {
    }

    public Owner(int travellerId, String airlineName, double income) {
       this.travellerId = travellerId;
       this.airlineName = airlineName;
       this.income = income;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTravellerId() {
        return this.travellerId;
    }
    
    public void setTravellerId(int travellerId) {
        this.travellerId = travellerId;
    }
    public String getAirlineName() {
        return this.airlineName;
    }
    
    public void setAirlineName(String airlineName) {
        this.airlineName = airlineName;
    }
    public double getIncome() {
        return this.income;
    }
    
    public void setIncome(double income) {
        this.income = income;
    }




}


