package hibernate;
// Generated Jan 25, 2018 5:49:05 PM by Hibernate Tools 4.3.1



/**
 * Routes generated by hbm2java
 */
public class Routes  implements java.io.Serializable {


     private Integer id;
     private String airline;
     private String code;
     private String fromap;
     private String toap;
     private int airplaneid;
     private float price;
     private int booked;
     private int activestatus;

    public Routes() {
    }

    public Routes(String airline, String code, String fromap, String toap, int airplaneid, float price, int booked, int activestatus) {
       this.airline = airline;
       this.code = code;
       this.fromap = fromap;
       this.toap = toap;
       this.airplaneid = airplaneid;
       this.price = price;
       this.booked = booked;
       this.activestatus = activestatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAirline() {
        return this.airline;
    }
    
    public void setAirline(String airline) {
        this.airline = airline;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getFromap() {
        return this.fromap;
    }
    
    public void setFromap(String fromap) {
        this.fromap = fromap;
    }
    public String getToap() {
        return this.toap;
    }
    
    public void setToap(String toap) {
        this.toap = toap;
    }
    public int getAirplaneid() {
        return this.airplaneid;
    }
    
    public void setAirplaneid(int airplaneid) {
        this.airplaneid = airplaneid;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getBooked() {
        return this.booked;
    }
    
    public void setBooked(int booked) {
        this.booked = booked;
    }
    public int getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(int activestatus) {
        this.activestatus = activestatus;
    }




}


